AWSTemplateFormatVersion: "2010-09-09"
Resources:

### BUCKET

  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: test-bucket-lambda-fdx-202204-cf-deployment
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain