AWSTemplateFormatVersion: "2010-09-09"
Resources:

### BUCKET

  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: deployment-fdx-202204-cf
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

# SSM

  DeploymentBucketName:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: "/test/trends/deployment-bucketname"
      Value: !Ref DeploymentBucket